// <auto-generated />
using System;
using Firma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Firma.Data.Migrations
{
    [DbContext(typeof(FirmaDbContext))]
    partial class FirmaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Firma.Data.Entities.Dzial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Dzialy");
                });

            modelBuilder.Entity("Firma.Data.Entities.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImieKontakt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaFirmy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NazwiskoKontakt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Firma.Data.Entities.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataZatrudnienia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZwolnienia")
                        .HasColumnType("date");

                    b.Property<int?>("DzialId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StanowiskoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DzialId");

                    b.HasIndex("StanowiskoId");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("Firma.Data.Entities.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataRozpoczecia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZakonczenia")
                        .HasColumnType("date");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.ToTable("Projekty");
                });

            modelBuilder.Entity("Firma.Data.Entities.Sprzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataZakupu")
                        .HasColumnType("date");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumerSeryjny")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Wartosc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.ToTable("Sprzet");
                });

            modelBuilder.Entity("Firma.Data.Entities.Stanowisko", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PensjaMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PensjaMin")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Stanowiska");
                });

            modelBuilder.Entity("Firma.Data.Entities.Urlop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataDo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOd")
                        .HasColumnType("date");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.ToTable("Urlopy");
                });

            modelBuilder.Entity("Firma.Data.Entities.Zadanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("Priorytet")
                        .HasColumnType("int");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TerminRealizacji")
                        .HasColumnType("date");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.HasIndex("ProjektId");

                    b.ToTable("Zadania");
                });

            modelBuilder.Entity("Firma.Data.Entities.Pracownik", b =>
                {
                    b.HasOne("Firma.Data.Entities.Dzial", "Dzial")
                        .WithMany("Pracownicy")
                        .HasForeignKey("DzialId");

                    b.HasOne("Firma.Data.Entities.Stanowisko", "Stanowisko")
                        .WithMany("Pracownicy")
                        .HasForeignKey("StanowiskoId");

                    b.Navigation("Dzial");

                    b.Navigation("Stanowisko");
                });

            modelBuilder.Entity("Firma.Data.Entities.Projekt", b =>
                {
                    b.HasOne("Firma.Data.Entities.Klient", "Klient")
                        .WithMany("Projekty")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("Firma.Data.Entities.Sprzet", b =>
                {
                    b.HasOne("Firma.Data.Entities.Pracownik", "Pracownik")
                        .WithMany()
                        .HasForeignKey("PracownikId");

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("Firma.Data.Entities.Urlop", b =>
                {
                    b.HasOne("Firma.Data.Entities.Pracownik", "Pracownik")
                        .WithMany("Urlopy")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("Firma.Data.Entities.Zadanie", b =>
                {
                    b.HasOne("Firma.Data.Entities.Pracownik", "Pracownik")
                        .WithMany("Zadania")
                        .HasForeignKey("PracownikId");

                    b.HasOne("Firma.Data.Entities.Projekt", "Projekt")
                        .WithMany("Zadania")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Firma.Data.Entities.Dzial", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("Firma.Data.Entities.Klient", b =>
                {
                    b.Navigation("Projekty");
                });

            modelBuilder.Entity("Firma.Data.Entities.Pracownik", b =>
                {
                    b.Navigation("Urlopy");

                    b.Navigation("Zadania");
                });

            modelBuilder.Entity("Firma.Data.Entities.Projekt", b =>
                {
                    b.Navigation("Zadania");
                });

            modelBuilder.Entity("Firma.Data.Entities.Stanowisko", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
